version: '3.7'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_db:/data/db
      - mongodb_configdb:/data/configdb
volumes:
  mongodb_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongodb-volume/db
  mongodb_configdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongodb-volume/configdb
