server:
    error:
        include-message: always
spring:
    data:
        mongodb:
            auto-index-creation: true
            authentication-database: admin
            username: lumba
            password: lumba
            database: history
            port: 27017
            host: localhost
    servlet:
        multipart:
            max-file-size: 256MB
            max-request-size: 256MB
            enabled: true
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG